### ISSUE TITLE
MySQL max connections

### ISSUE THREAD

**Issue by mobilemindtec** [treefrogframework/treefrog-framework#380]
Hello everyone,

How can I set a connection limit with mysql? I have a relatively simple application that sends e-mails coming from several other applications. When I upload the application and execute some jobs, the system locates 20 connections with the database and does not release any more. I tried reducing the MaxThreadsPerAppServer setting to 10, but after running a few jobs the system freeze. I'd like to limit this number of connections to 5 or 10. This system doesn't require a lot of workload and yet it takes up a significant amount of my database connections. Is there any solution?

Thanks!

**Comment by treefrogframework** [comment]
The maximum number of connections is [MPM.thread.MaxAppServers * MPM.thread.MaxThreadsPerAppServer] in the case of MultiProcessingModule=thread.
The framework connects to the database only when it actually needs to access it. If there is no communication for a certain period of time, the connection is closed.
I think the system freeze may be caused by other problems.

Check the connections in mysql.
 > show status like 'Threads_connected';
